/*
 * Hankel transform of a form factor that is only known at a set of points
 * (measured data, or output from another code), rather than as a formula.
 *
 * The table is turned into a PCHIP spline with cubic_interp_create, and the
 * spline is wrapped in a form_factor_f callback. The wrapper is where the
 * real work is: it has to define the form factor *outside* the tabulated
 * range, because every strategy evaluates it far beyond the data. See the
 * comment on tabulated_form_factor below.
 *
 * To keep the example self-checking, the "measured" table is generated by
 * sampling the built-in g_dab form factor, so the result can be compared
 * against transforming g_dab analytically. Real data would be read from a
 * file instead.
 */

#include <math.h>
#include <stddef.h>
#include <stdio.h>

#include "form_factors.h"
#include "interp_cubic.h"
#include "libhankel.h"

#define ARRAY_LEN 19
#define N_TABLE 200

/* Context for the tabulated form factor: the spline plus everything needed
 * to continue the curve past the ends of the table. */
typedef struct {
    cubic_interp_t *spline;
    double q_lo, q_hi; /* first and last tabulated q          */
    double f_lo, f_hi; /* form factor at those two points     */
    double p;          /* high-q power-law exponent, f ~ q^-p */
} tabulated_ctx;

/*
 * The form factor callback.
 *
 * cubic_interp_eval returns NaN outside [q_lo, q_hi], and the quadrature
 * nodes chosen by the strategies go a very long way outside any real table
 * (DHT_Anderson_801 asks for q from about 1e-15 up to 3e+20). Returning that
 * NaN straight to the strategy makes the whole transform NaN.
 *
 * So the two tails have to be defined explicitly:
 *
 *   q below the table: hold the curve flat at f(q_lo). Physically this is
 *       the q -> 0 plateau, and it is harmless numerically because the
 *       Hankel integrand carries a factor of q that kills the region anyway.
 *
 *   q above the table: continue as a power law f ~ q^-p. This matters more
 *       than it looks. The integrand is f(q) * J0(q*r) * q, and for large z
 *       J0(z) ~ sqrt(2 / (pi * z)) * cos(...), so the integrand behaves like
 *       q^(1/2 - p). It only converges for p > 3/2. Holding the curve flat
 *       instead (p = 0) leaves an oscillating integrand whose amplitude
 *       *grows* like sqrt(q), and the integral does not converge at all.
 *       Truncating to zero converges but puts ringing into the result.
 *
 * Porod's law gives p = 4 for a sharp interface, comfortably inside the
 * convergent range. Here p is estimated from the slope of the last part of
 * the table instead, which is what you would do with real data.
 */
double tabulated_form_factor(double q, void *f_ctx) {
    tabulated_ctx *ctx = (tabulated_ctx *)f_ctx;

    if (q <= ctx->q_lo) {
        return ctx->f_lo;
    }
    if (q >= ctx->q_hi) {
        return ctx->f_hi * pow(q / ctx->q_hi, -ctx->p);
    }
    return cubic_interp_eval(ctx->spline, q);
}

int main(void) {

    int nu = 0;

    /* ---- Stand in for measured data ------------------------------------
     * Sample the built-in g_dab form factor on a log-spaced grid. Log
     * spacing is the natural choice for scattering data, which covers
     * several decades in q. */
    double params_gdab[] = {10.0, 0.5, 1e-4};
    form_factor_ctx ctx_gdab = {.params = params_gdab};

    double q_table[N_TABLE], f_table[N_TABLE];
    double q_first = 1e-3, q_last = 10.0;

    for (int i = 0; i < N_TABLE; i++) {
        q_table[i] = q_first * pow(q_last / q_first, (double)i / (N_TABLE - 1));
        f_table[i] = form_factor_g_dab(q_table[i], &ctx_gdab);
    }

    /* ---- Build the spline ---------------------------------------------- */
    cubic_interp_t *spline = cubic_interp_create(q_table, f_table, N_TABLE);
    if (spline == NULL) {
        fprintf(stderr, "failed to build spline (need n >= 4 and increasing q)\n");
        return 1;
    }

    /* ---- Estimate the high-q slope from the tail of the table -----------
     * A straight-line fit in log-log space across the last 40 points. */
    int last = N_TABLE - 1, back = N_TABLE - 40;
    double p = -log(f_table[last] / f_table[back]) / log(q_table[last] / q_table[back]);

    tabulated_ctx ctx_tab = {.spline = spline,
                             .q_lo = q_table[0],
                             .q_hi = q_table[last],
                             .f_lo = f_table[0],
                             .f_hi = f_table[last],
                             .p = p};

    printf("high-q exponent estimated from the table: p = %.3f\n\n", p);

    /* ---- Transform ------------------------------------------------------ */
    strategy_params strategy_params_gdab = {.n_eval = 250, .eps_rel = 1e-9};

    double r_array[ARRAY_LEN] = {
        15.,  18.5, 22.,  25.6, 29.1, 32.7, 36.2, 39.7, 43.3, 46.9,
        50.4, 53.9, 57.5, 61.1, 64.5, 68.1, 71.6, 75.2, 78.75,
    };

    double result_tabulated[ARRAY_LEN];
    double result_analytic[ARRAY_LEN];

    int status = hankel_transform(nu, tabulated_form_factor, r_array, ARRAY_LEN, &ctx_tab,
                                  result_tabulated, "QWE_Key", strategy_params_gdab);
    if (status != 0) {
        fprintf(stderr, "transform of tabulated data failed with status %d\n", status);
        cubic_interp_destroy(spline);
        return 1;
    }

    /* The same transform straight from the formula, for comparison. */
    status = hankel_transform(nu, form_factor_g_dab, r_array, ARRAY_LEN, &ctx_gdab,
                              result_analytic, "QWE_Key", strategy_params_gdab);
    if (status != 0) {
        fprintf(stderr, "analytic transform failed with status %d\n", status);
        cubic_interp_destroy(spline);
        return 1;
    }

    printf("%8s %18s %18s %12s\n", "r", "tabulated", "analytic", "rel. error");
    for (int i = 0; i < ARRAY_LEN; i++) {
        double rel_err = fabs(result_tabulated[i] - result_analytic[i]) / fabs(result_analytic[i]);
        printf("%8.2f %18.10g %18.10g %12.2e\n", r_array[i], result_tabulated[i],
               result_analytic[i], rel_err);
    }

    /* ---- Clean up -------------------------------------------------------
     * Every non-NULL cubic_interp_create must be matched by exactly one
     * destroy. The spline has to outlive the last hankel_transform call that
     * can reach it through the context. */
    cubic_interp_destroy(spline);

    return 0;
}
