/*
 * Hankel transform of a form factor known only at a set of points - measured
 * data, or output from another code - rather than as a formula.
 *
 * tabulated_ff_create interpolates the table and, just as importantly, defines
 * the curve outside it: every strategy evaluates the form factor far beyond
 * any real dataset, so what happens out there decides whether the transform
 * converges at all. This example uses a power-law tail; see the Tabulated form
 * factors page for the alternative and for how to choose.
 *
 * The "measured" table is generated by sampling the built-in g_dab form
 * factor, so the answer can be checked against transforming g_dab
 * analytically. Real data would be read from a file instead.
 */

#include <math.h>
#include <stdio.h>

#include "form_factors.h"
#include "libhankel.h"
#include "tabulated_ff.h"

#define ARRAY_LEN 19
#define N_TABLE 200

int main(void) {

    int exit_code = 1;
    tabulated_ff_t *ff = NULL;

    /* ---- Stand in for measured data -------------------------------------
     * Log-spaced, the natural grid for scattering data, which covers several
     * decades in q. The table stops at q = 1, about where a real measurement
     * would run out, so the tail below is doing real work here. */
    double params_gdab[] = {10.0, 0.5, 1e-4};
    form_factor_ctx ctx_gdab = {.params = params_gdab};

    double q_table[N_TABLE], f_table[N_TABLE];
    double q_first = 1e-3, q_last = 1.0;

    for (int i = 0; i < N_TABLE; i++) {
        q_table[i] = q_first * pow(q_last / q_first, (double)i / (N_TABLE - 1));
        f_table[i] = form_factor_g_dab(q_table[i], &ctx_gdab);
    }

    /* ---- Build the tabulated form factor ---------------------------------
     * Above the last point the curve continues as f ~ q^-p, and passing 0 as
     * the exponent asks for p to be fitted from the high-q end of the table,
     * which is what you would do with real data. Below the first point the
     * value is held flat, the physical q -> 0 plateau.
     *
     * The transform converges only for p > 3/2, and create returns -14 rather
     * than admitting a divergent tail - so a table that stops before its
     * asymptote is rejected here instead of producing a plausible wrong answer
     * later. */
    int status =
        tabulated_ff_create(q_table, f_table, N_TABLE, TABULATED_TAIL_POWER_LAW, 0.0, &ff);
    if (status != 0) {
        fprintf(stderr, "failed to build the tabulated form factor, status %d\n", status);
        return exit_code;
    }

    /* ---- Transform -------------------------------------------------------
     * tabulated_ff_eval already has the shape of a form_factor_f, and the
     * handle is its own context, so it goes straight into hankel_transform
     * with no wrapper to write. */
    int nu = 0;
    strategy_params strategy_params_gdab = {.n_eval = 250, .eps_rel = 1e-9};

    double r_array[ARRAY_LEN] = {
        15.,  18.5, 22.,  25.6, 29.1, 32.7, 36.2, 39.7, 43.3, 46.9,
        50.4, 53.9, 57.5, 61.1, 64.5, 68.1, 71.6, 75.2, 78.75,
    };

    double result[ARRAY_LEN];
    double result_analytic[ARRAY_LEN];

    status = hankel_transform(nu, tabulated_ff_eval, r_array, ARRAY_LEN, ff, result, "QWE_Key",
                              strategy_params_gdab);
    if (status != 0) {
        fprintf(stderr, "transform of the tabulated data failed with status %d\n", status);
        goto cleanup;
    }

    /* The same transform straight from the formula, for comparison. */
    status = hankel_transform(nu, form_factor_g_dab, r_array, ARRAY_LEN, &ctx_gdab, result_analytic,
                              "QWE_Key", strategy_params_gdab);
    if (status != 0) {
        fprintf(stderr, "analytic transform failed with status %d\n", status);
        goto cleanup;
    }

    /* The two columns track each other to around one part in a million. */
    printf("%8s %18s %18s %12s\n", "r", "analytic", "tabulated", "rel. error");
    for (int i = 0; i < ARRAY_LEN; i++) {
        double err = fabs(result[i] - result_analytic[i]) / fabs(result_analytic[i]);
        printf("%8.2f %18.10g %18.10g %12.2e\n", r_array[i], result_analytic[i], result[i], err);
    }

    exit_code = 0;

    /* The handle must outlive the last hankel_transform call that can reach
     * it, and be destroyed exactly once. tabulated_ff_destroy ignores NULL. */
cleanup:
    tabulated_ff_destroy(ff);

    return exit_code;
}
