"""
Write the sasmodels copy of a digital filter's abscissae and weights.

``sasmodels`` applies the filter itself, in numpy, so it needs the node table
but nothing else from LibHankel -- see ``dht_sesans.py`` for why a filter, and
only a filter, fits the ``q_calc`` contract that sasmodels resolution objects
have to satisfy. Copying the table rather than importing it keeps sasmodels
free of a compiled dependency, at the cost of a second copy of the constants.

This script is that copy's provenance. Run it to regenerate the file, rather
than editing the numbers by hand::

    python export_filter_table.py ../../../sasmodels/sasmodels/sesans_filter.py

Only the nu = 0 weights are written. SESANS is a J0 transform, so the J1
column of the table is never read.
"""

import argparse
import sys

import libhankel

#: The filter sasmodels uses. 201 points is the longest Key filter, and the
#: one the benchmarks in this directory were run with.
STRATEGY = "DHT_Key_201"

HEADER = '''"""
Abscissae and weights of the {strategy} digital filter, for
:class:`.sesans.DHTSesansTransform`.

The filter evaluates a J0 Hankel transform at spin-echo length xi as::

    sum(I(a[i]/xi) * (a[i]/xi) * w[i] / xi)

so the q values at which I(q) is needed follow from the table and from xi
alone, and are known before any model is evaluated.

Generated by ``export_filter_table.py`` in LibHankel's ``examples/sesans``;
do not edit by hand. The coefficients themselves are Kerry Key's published
Hankel filters, not original to either project.
"""

import numpy as np

#: Filter abscissae, dimensionless. The q at which I(q) is needed is
#: ``ABSCISSAE / xi``.
ABSCISSAE = np.array([
'''

MIDDLE = '''])

#: Filter weights for the J0 transform, in the same order as
#: :data:`ABSCISSAE`.
WEIGHTS = np.array([
'''

FOOTER = '''])
'''


def render(strategy=STRATEGY):
    # type: (str) -> str
    """Return the text of the sasmodels module for *strategy*."""
    abscissae, weights = libhankel.dht_nodes(strategy, 0)

    def column(values):
        return "".join("    %r,\n" % value for value in values)

    return (HEADER.format(strategy=strategy)
            + column(abscissae) + MIDDLE + column(weights) + FOOTER)


def main(argv=None):
    # type: (list | None) -> int
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", nargs="?",
                        help="file to write; defaults to stdout")
    parser.add_argument("--strategy", default=STRATEGY,
                        help="filter to export (default: %(default)s)")
    opts = parser.parse_args(argv)

    text = render(opts.strategy)
    if opts.output is None:
        sys.stdout.write(text)
    else:
        with open(opts.output, "w") as fid:
            fid.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
